version: 2.1

defaults: &defaults
  docker:
    - image: rust

jobs:
  test: &test-template
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run pure rust tests
          command: cargo test --no-default-features --features pure
      - run:
          name: Run openssl rust tests
          command: cargo test --no-default-features --features openssl

  test-beta:
    <<: *test-template
    docker:
      - image: instrumentisto/rust:beta
  test-nightly:
    <<: *test-template
    docker:
      - image: rustlang/rust:nightly

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set token
          command: cargo login $CARGO_DEPLOY_TOKEN
      - run:
          name: Publish package
          command: cargo publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - test-beta:
          filters:
            tags:
              only: /^v.*/
      - test-nightly:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
            - test-beta
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
